In [41]:
import pandas as pd 
import numpy as np

Loading the Dataset:
In this section, we load the dataset and examine its structure
to understand the number of rows, columns, and data types

In [42]:
sales = pd.read_csv(r"C:\Users\Kingsley Omah\Desktop\Datasets\online_retail.csv")
sales.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

UNDERSTANDING THE DATASTRUCTURE

In [43]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [44]:
sales.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

CHECKING FOR DATA TYPES FOR EACH COLUMN : This helps to know the column we need to convert to the appropraite column data type

In [45]:
sales.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

DATA CLEANING TO ENSURE ACCURATE ANALYSIS

Converting InvoiceDate column to to datetime and InvoiceNo to interger

In [46]:
sales['InvoiceDate'] = pd.to_datetime(sales['InvoiceDate'])
sales['InvoiceNo'] = sales['InvoiceDate'].astype(int)

DROPPING DUPLICATE : Duplicate rows were removed to prevent double counting and ensure accurate analysis.

In [47]:
sales.drop_duplicates(inplace=True)

CHECKING FOR MISSING VALUES

In [48]:
sales.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1453
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     134497
Country             0
dtype: int64

Handling missing values

In [49]:
print('The number of missing values in Description column are:',sales['Description'].isnull().sum())

The number of missing values in Description column are: 1453

In [50]:
sales['Description']=sales['Description'].fillna('Unknown Product')

Missing product descriptions were filled with "Unknown Product" to preserve all sales transactions for product analysis.

In [51]:
print('The number of missing values in CustomerID column are:',sales['CustomerID'].isnull().sum())

The number of missing values in CustomerID column are: 134497

In [52]:
df = sales.copy()
df_customers = df.dropna(subset=['CustomerID'])

CustomerID has 135037  mising values which does not really affect other analysis except customer segment analysis,i created a copy of the
original dataframe and dropped the missing ID which will be used for custor segment analysis to ensure accurate customer segmentation, while 
remaining included in overall sales and product analysis.

In [53]:
df_customers.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

Cross checking for missing values in the copied dataframe

Rows with negative unit prices were removed because they represent data entry errors. 
Negative quantities were retained to capture product returns.

In [54]:
sales = sales[sales['UnitPrice'] > 0]

In [55]:
sales.dtypes

InvoiceNo               int64
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [56]:
sales.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,1291191960000000000,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,1291191960000000000,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,1291191960000000000,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,1291191960000000000,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,1291191960000000000,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

EXPLORATORY DATAANALYSIS (EDA)

NEW COLUMNS FOR ANALYSIS

In [57]:

sales['Revenue'] = sales['Quantity'] * sales['UnitPrice']
sales['Month'] = sales['InvoiceDate'].dt.month
sales['DayOfWeek'] = sales['InvoiceDate'].dt.day_name()
sales['Hour'] = sales['InvoiceDate'].dt.hour

BASIC OVERVIEW

-What is the total revenue generated?

In [58]:
sales['Revenue'] = sales['Quantity'] * sales['UnitPrice']
print('The total revenue generated is :',sales['Revenue'].sum())

The total revenue generated is : 9742511.984000001

-How many orders and unique customers are there?

In [59]:

Total_Orders =sales['InvoiceNo'].nunique()
Unique_customers =sales['CustomerID'].nunique()
print('The total number of orders are:',Total_Orders)
print('The unique customers are:',Unique_customers )

The total number of orders are: 21802
The unique customers are: 4371

Unique Customers:

The number of different customers who bought something. Each customer is counted only once, even if they bought many times.

-What is the total quantity of items sold?

In [60]:
Total = sales['Quantity'].sum()
print('The total quantity of items sold are :',Total)

The total quantity of items sold are : 5295681

-What is the average order value?

In [61]:
AOV = sales.groupby('InvoiceNo')['Revenue'].sum().mean()
print('The average order value is:',AOV)

The average order value is: 446.86322282359424

B. CUSTOMER ANALYSIS

-Who are the top 10 customers by total revenue?

In [62]:
Top_ten = sales.groupby('CustomerID')['Revenue'].sum().sort_values(ascending=False).head(10)
Top_ten_df = Top_ten.reset_index()
Top_ten_df.columns = ['CustomerID', 'TotalRevenue']
print(Top_ten_df)

   CustomerID  TotalRevenue
0     14646.0     279489.02
1     18102.0     255522.49
2     17450.0     187322.17
3     14911.0     132458.73
4     12415.0     123725.45
5     14156.0     113214.59
6     17511.0      88125.38
7     16684.0      65892.08
8     13694.0      62690.54
9     15311.0      59284.19

-Which customers buy most frequently (number of orders)?

In [63]:
orders_per_customer = sales.groupby('CustomerID')['InvoiceNo'].nunique()
top_customers = orders_per_customer.sort_values(ascending=False).head(10)
top_customers_df = top_customers.reset_index()
top_customers_df.columns = ['CustomerID', 'NumberOfOrders']
print(top_customers_df)

   CustomerID  NumberOfOrders
0     14911.0             248
1     12748.0             224
2     17841.0             168
3     14606.0             129
4     15311.0             118
5     13089.0             114
6     12971.0              86
7     14527.0              85
8     13408.0              77
9     14646.0              76

-How many customers made only one purchase?

In [64]:
total_one_purchase = (sales.groupby('CustomerID')['InvoiceNo'].nunique() == 1).sum()
print(total_one_purchase)

1313

-What is the distribution of customer revenue (e.g., low, medium, high)?

In [65]:
customer_revenue = sales.groupby('CustomerID')['Revenue'].sum()
customer_segments = pd.qcut(customer_revenue, q=3, labels=['Low', 'Medium', 'High'])
segment_distribution = customer_segments.value_counts()
print(segment_distribution)

Revenue
Low       1457
Medium    1457
High      1457
Name: count, dtype: int64

Customers are grouped based on the total revenue they generate. 
They are classified into low, medium, and high revenue customers to better understand spending behavior.

 -Who are the customers with highest returns or cancellations?

In [66]:
returns = sales[sales['Quantity']<0]
highest_returns = returns.groupby('CustomerID')['Quantity'].count().sort_values(ascending=False).head()
highest_returns_df = highest_returns.reset_index()
highest_returns_df.columns = ['CustomerID',"Number of returns"]
highest_returns_df

   CustomerID  Number of returns
0     14911.0                226
1     17841.0                136
2     17511.0                113
3     15311.0                112
4     12607.0                101

I filtered the dataset to include only rows where the Quantity is less than 0 [negative quantities represent items 
that were returned by customers] and i picked the top 5

In [67]:
sales.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Month,DayOfWeek,Hour
0,1291191960000000000,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,12,Wednesday,8
1,1291191960000000000,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,12,Wednesday,8
2,1291191960000000000,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,12,Wednesday,8
3,1291191960000000000,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,12,Wednesday,8
4,1291191960000000000,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,12,Wednesday,8

C PRODUCT  ANALYSIS

-What are the top 10 products by quantity sold?

In [68]:
Top_ten = sales.groupby('Description')['Quantity'].count().sort_values(ascending = False)
print('The top 10 products by quantity sold are : ', Top_ten.head(10))

The top 10 products by quantity sold are :  Description
WHITE HANGING HEART T-LIGHT HOLDER    2351
REGENCY CAKESTAND 3 TIER              2187
JUMBO BAG RED RETROSPOT               2140
PARTY BUNTING                         1718
LUNCH BAG RED RETROSPOT               1623
ASSORTED COLOUR BIRD ORNAMENT         1488
SET OF 3 CAKE TINS PANTRY DESIGN      1464
PACK OF 72 RETROSPOT CAKE CASES       1367
LUNCH BAG  BLACK SKULL.               1322
NATURAL SLATE HEART CHALKBOARD        1269
Name: Quantity, dtype: int64

-Are there products with negative quantities (returns)?

In [69]:
negetive = sales[sales['Quantity'] < 0]
negetive.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Month,DayOfWeek,Hour
141,1291196460000000000,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom,-27.50,12,Wednesday,9
154,1291196940000000000,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom,-4.65,12,Wednesday,9
235,1291199040000000000,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom,-19.80,12,Wednesday,10
236,1291199040000000000,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,-6.96,12,Wednesday,10
237,1291199040000000000,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,-6.96,12,Wednesday,10

Firstly, I filtered the dataset to contain only negetive quantities

In [70]:
negetive = sales[sales['Quantity'] < 0]
print(negetive['Quantity'].count())

9251

Numbers of returns

-Which products are rarely sold or low demand items

In [71]:
Top_ten = sales.groupby('Description')['Quantity'].count().sort_values()
print( Top_ten.head(10))

Description
*Boombox Ipod Classic                 1
 TOADSTOOL BEDSIDE LIGHT              1
WRAP  PINK FLOCK                      1
 I LOVE LONDON MINI RUCKSACK          1
DOORKNOB CERAMIC IVORY                1
WRAP BLUE RUSSIAN FOLKART             1
WHITE DOVE HONEYCOMB PAPER GARLAND    1
WHITE FRANGIPANI HAIR CLIP            1
WEEKEND BAG VINTAGE ROSE PAISLEY      1
WHITE ANEMONE ARTIFICIAL FLOWER       1
Name: Quantity, dtype: int64

-Which products are frequently returned

In [72]:
negetive = sales[sales['Quantity'] < 0]
returned_products = negetive.groupby('Description')['Quantity'].sum().sort_values()
print(returned_products.head())

Description
PAPER CRAFT , LITTLE BIRDIE           -80995
MEDIUM CERAMIC TOP STORAGE JAR        -74494
ROTATING SILVER ANGELS T-LIGHT HLDR    -9376
Manual                                 -4066
FAIRY CAKE FLANNEL ASSORTED COLOUR     -3150
Name: Quantity, dtype: int64

D. COUNTRY AND REGIONAL ANALYSIS

-Which countries generate the highest revenue?

In [73]:
H_revenue =sales.groupby('Country')['Revenue'].sum().sort_values(ascending = False).head()
Highest_revenue = H_revenue.reset_index()
Highest_revenue.columns = ['Country',"Revenue Generated"]
Highest_revenue

          Country  Revenue Generated
0  United Kingdom        8183651.214
1     Netherlands         284661.540
2            EIRE         262993.380
3         Germany         221491.470
4          France         197317.110

-What is the average order value per country?

In [74]:
sales.groupby('Country')['Revenue'].mean().head()
#i highlight just the first five country

Country
Australia    109.171131
Austria       25.322494
Bahrain       28.863158
Belgium       19.773301
Brazil        35.737500
Name: Revenue, dtype: float64

E. TIME BASED ANALYSIS

-How do monthly sales trend over time?

In [75]:
monthly_revenue = sales.resample('ME', on='InvoiceDate')['Revenue'].sum()
monthly_revenue

InvoiceDate
2010-12-31     745858.240
2011-01-31     558368.130
2011-02-28     496775.030
2011-03-31     681318.050
2011-04-30     491919.041
2011-05-31     720972.250
2011-06-30     689391.150
2011-07-31     678964.781
2011-08-31     703510.580
2011-09-30    1017398.282
2011-10-31    1069265.490
2011-11-30    1456089.800
2011-12-31     432681.160
Freq: ME, Name: Revenue, dtype: float64

-Which day of the week has the highest sales?

In [76]:
week = sales.groupby('DayOfWeek')['Revenue'].sum()
print('The day of the week with highest sales is:', week.sort_values(ascending = False).head(1))

The day of the week with highest sales is: DayOfWeek
Thursday    2108500.34
Name: Revenue, dtype: float64

-How does revenue vary by hour of the day?

In [77]:
hour = sales.groupby('Hour')['Revenue'].sum()
hour

Hour
6        -497.350
7       31009.320
8      281723.020
9      766138.671
10    1325888.461
11    1146255.000
12    1357409.850
13    1172313.830
14    1113217.861
15    1184583.200
16     727485.520
17     434834.541
18     140365.040
19      45864.930
20      15920.090
Name: Revenue, dtype: float64